name: Enforce Correct Package Versions

# This action runs on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  fix-and-commit:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code that was just pushed
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need a token to be able to push back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Check if the bad version exists. If not, the job ends successfully.
      # The "|| true" ensures the workflow doesn't fail if the file is already correct.
      - name: Check for and fix incorrect Tailwind versions
        run: |
          # Use sed to find and replace the downgraded versions with the correct ones
          sed -i 's/"tailwindcss": "4.0.0"/"tailwindcss": "^4.1.9"/' package.json
          sed -i 's/"@tailwindcss/vite": "4.0.0"/"@tailwindcss/vite": "^4.1.4"/' package.json
          echo "Checked and fixed versions if necessary."

      # Step 3: Use a pre-built action to automatically commit and push any changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Auto-correct Tailwind versions downgraded by v0"
          branch: main
          # Optional: Add a file pattern to only commit if package.json changed
          file_pattern: package.json
