name = "v0-plum-candy-website"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[services]]
binding = "EMAIL_SENDER"
service = "contact-form-email"  # Updated to match the actual worker name from the instructions
